---
abstract: 'multi-language user-agent strings parsers (perl implementation)'
author:
  - 'TAGOMORI Satoshi <tagomoris {at} gmail.com>'
build_requires:
  Test::More: 0.98
  YAML: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.6, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Woothee
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Woothee:
    file: lib/Woothee.pm
    version: v0.3.6
  Woothee::Appliance:
    file: lib/Woothee/Appliance.pm
    version: v0.3.6
  Woothee::Browser:
    file: lib/Woothee/Browser.pm
    version: v0.3.6
  Woothee::Crawler:
    file: lib/Woothee/Crawler.pm
    version: v0.3.6
  Woothee::DataSet:
    file: lib/Woothee/DataSet.pm
    version: 0
  Woothee::Misc:
    file: lib/Woothee/Misc.pm
    version: v0.3.6
  Woothee::MobilePhone:
    file: lib/Woothee/MobilePhone.pm
    version: v0.3.6
  Woothee::OS:
    file: lib/Woothee/OS.pm
    version: v0.3.6
  Woothee::Util:
    file: lib/Woothee/Util.pm
    version: v0.3.6
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/woothee/woothee-perl/issues
  homepage: https://github.com/woothee/woothee-perl
  repository: git://github.com/woothee/woothee-perl.git
version: 0.3.6
x_contributors:
  - 'TAGOMORI Satoshi <tagomoris@gmail.com>'
