---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Find::Rule: 0
  File::Spec: 0
  FindBin: 0
  Path::Class: 0
  Test::More: 0
  Time::HiRes: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Woothee
no_index:
  directory:
    - inc
    - t
version: 0.2.1
